# Generated by Django 6.0.6 on 2026-06-03 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Planta',
                'verbose_name_plural': 'Tipos de Plantas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=200)),
                ('especie_cientifica', models.CharField(blank=True, max_length=200, null=True)),
                ('cuidados', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='plantas_fotos/')),
                ('tipo_planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantas', to='plantas.tipoplanta')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['nombre_comun'],
            },
        ),
    ]
